### ISSUE TITLE
Error : 401 - Unauthorized, Retrying after 10 Second

### ISSUE THREAD

**Issue by ngocbae98** [Rambeboy/midas-rwa-bot#1]
Error : 401 - Unauthorized, Retrying after 10 Second

**Comment by Rambeboy** [comment]
use new query_id

**Comment by ngocbae98** [comment]
> use new query_id

Your bot run with session

**Comment by Rambeboy** [comment]
Run with query

**Comment by ngocbae98** [comment]
> Run with query

(If You Use Telegram Sessions) To configure the app, run

nano config/config.js

What??

**Comment by Rambeboy** [comment]
If you want to use a query, hold down nano config/config.js, you don't need to fill it in, just run the bot, then select number 1 create account, then select number 2 query.
